---
title: " ANR Phytovirus - plants "
author: "Oumaima Moubset, Virginie Ravigné, Frédéric Mahé"
date: '`r format(Sys.time(), "%d %B %Y")`'

output:
  rmarkdown::html_document:
    theme: lumen
    toc: yes
    toc_float: TRUE
    keep_md: yes
    code_folding: hide
---

```{r setup, include=FALSE}
rm(list = ls()) # remove all objects before starting
knitr::opts_chunk$set(echo = TRUE)
```

------------------------------------------------------------------------

#### Load packages

```{r packages, message=FALSE}
library(readxl)
library(tidyverse)
library(janitor)
library(purrr)
library(ggplot2)
```

## Generate the plant and quadrat data sets from field reports in data

Summaries of the plant and the quadrat data sets.

```{r plants, message=FALSE}
source("./scripts/Distrib_cover_fred.R")
plant_data %>%
  select(
    Year,
    Locality,
    Grid,
    Quadrat,
    Vegetation,
    Total_cover,
    Total_cover_max,
    Plant_richness,
    Plant_diversity
  ) %>% 
  distinct() -> quadrat_data

quadrat_data %>% summary()

plant_data %>% summary()
```


# Exploring plant distributions

## Distribution of total cover

Total plant cover in quadrats may be measured in different ways. A
Vegetation index is pifometrically measured in situ. It should more or
less relate to `Total_cover`, the sum of the mean of the cover ranges
over all plants, and `Total_cover_max`, the sum of the superior limit
of cover ranges over plants. `Total_cover` and `Total_cover_max`
should not be less than `Vegetation`. Values of `Total_cover` and
`Total_cover_max` exceeding `Vegetation` could indicate that plants
are disposed into several layers.

`Total_cover` and `Vegetation` correlate nicely :

```{r vegetation, message=FALSE}
quadrat_data %>%
  filter(Locality == "CAM") %>%
  ggplot(., aes(x = Vegetation, y = Total_cover)) +
  geom_smooth(method = "lm", se = T) +
  geom_point(position = position_jitter(0.1)) +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Different measures of total cover")

# quadrat_data %>%
#   filter(Locality == "CAM") %>%
#   ggplot(., aes(x = Vegetation, y = Total_cover_max)) +
#   geom_smooth(method = "lm", se = T) +
#   geom_point(position = position_jitter(0.1)) +
#   theme(axis.text.x = element_text(angle = 90)) 
```

Distribution of total cover over grids :

```{r total_cover, message=FALSE}
ggplot(quadrat_data, aes(fill = Locality, y = Total_cover, x = Grid)) +
  geom_boxplot(position = "dodge") +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Distribution of total cover over all grids of ANG, BDX and CAM")

# An alternative visualization with an frequency histogram 
# ggplot(quadrat_data, aes(x = Total_cover, fill = Locality)) +
#   geom_histogram(position = "dodge") +
#   ggtitle("Distribution of total cover over all grids of ANG, BDX and CAM")
```


## Ranges of observed plant richness and diversity

NB : Richness as a number of plant species. Diversity as a Hill number
of order 1 (i.e., exp(Shannon)).

```{r diversity_richness, message = FALSE}
# All localities grouped together
# ggplot(quadrat_data, aes(x = Plant_richness, y = Plant_diversity)) +
#   geom_point() +
#   geom_smooth(method = "lm", se = T) +
#   theme(axis.text.x = element_text(angle = 90)) +
#   ggtitle("Richness-diversity")

#By locality
ggplot(quadrat_data, aes(x = Plant_richness, y = Plant_diversity)) +
  geom_point() +
  geom_smooth(method = "lm", se = T) +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_grid(~ Locality) +
  ggtitle("Richness-diversity")
```

NB : It could be good to check the outlier at > 25 species. Maybe Hugo
took too much coffee that day...


## Distributions of abundances

Cover ranges can be viewed as measures of absolute abundance. Here the
variable `Cover_classes` accounts for the means of cover ranges.

```{r absolute_abundance, message = FALSE}
ggplot(plant_data, aes(x = Cover_classes)) +
  geom_histogram() +
  ggtitle("Distribution of cover classes over all grids of ANG, BDX and CAM")

ggplot(plant_data, aes(x = Cover_classes, fill = Locality)) +
  geom_histogram() +
  facet_grid( ~ Locality) +
  ggtitle("Distribution of cover classes in each locality")
```

Following a bold inspiration, let's compute relative abundances using
the normalized `Cover_classes` (`Cover_classes/sum(Cover_classes)` for
each plant in a quadrat):

```{r relative_abundance, message = FALSE}
ggplot(plant_data, aes(x = Relative_abundance)) +
  geom_histogram() +
  ggtitle("Distribution of relative abundances over all grids of ANG, BDX and CAM")
```

Now we take the log10 of this relative abundance. If the distribution
is flat, relative abundance follows a 1/x function (Barbier,
pers. comm.):

```{r log10_rel_ab, message = FALSE}
ggplot(plant_data, aes(x = log10(Relative_abundance))) +
  geom_histogram() +
  ggtitle("Distribution of log(relative abundances) over all grids of ANG, BDX and CAM")
```

Matthieu says that this is flat. Philippe would probably see a
cosinus. Other opinions?

```{r rel_ab_loc, message = FALSE}
ggplot(plant_data, aes(x = Relative_abundance, fill = Locality)) +
  geom_histogram() +
  facet_grid( ~ Locality) +
  ggtitle("Distribution of relative abundances in each locality")
```

Team blue wins.

## Abundance profiles

Ultimately, Matthieu needs something that may help simulating
realistic plant communities, i.e., a distribution of abundance
distributions. Here we provide such distributions by omitting plant
identities, ranking plants by decreasing relative abundance in each
quadrat and plotting the distribution of the abundance of the most
frequent plant, of the second most frequent plant and so on... we call
that abundance profiles.
 
```{r profile, message = FALSE}
ggplot(plant_data, aes(x = Rank, y = Relative_abundance)) +
  geom_point() +
  stat_summary(
    fun = median,
    geom = "line",
    size = 1,
    color = "orange"
  ) +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Abundance profiles")
```

NB : orange line = median

Same thing with boxplots :

```{r profile_with_boxplots, message = FALSE}
plant_data %>%
  filter(Locality == "CAM") %>%
  mutate(Rank_as_factor = as.factor(Rank)) %>%
  ggplot(., aes(x = Rank_as_factor, y = Relative_abundance)) +
  geom_boxplot() +
  geom_point(position = position_jitter(width = 0.1)) +
  stat_summary(
    fun = median,
    geom = "line",
    size = 1,
    color = "black"
  ) +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Abundance profiles")
```

```{r profile_by_locality, message = FALSE}
ggplot(plant_data, aes(x = Rank, y = Relative_abundance, col = Locality)) +
  geom_point() +
  stat_summary(
    fun = median,
    geom = "line",
    size = 1,
    color = "black"
  ) +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_grid( ~ Locality) +
  ggtitle("Abundance profiles by locality")
```

Awfully hard to read... but worthy. Here we separate abundance
profiles by richness classes (big boss order). Strangely, it seems
that communities with many plants are more democratic than communities
with few plants (not dominated by one or two abundant
plants). Artefact or not?

```{r profile_by_r, message = FALSE}
ggplot(plant_data,
       aes(x = Rank, y = Relative_abundance, color = Plant_richness)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_wrap( ~ Plant_richness) +
  ggtitle("Abundance profiles in each richness class")

```

```{r garbage, message = FALSE}
# As expected, there are now `r prettyNum(smallest_sample_size, scientific=FALSE, big.mark=",")` reads in all samples.
```

------------------------------------------------------------------------

```{r}
sessionInfo()
rm(list = ls())
```

```{r eval = FALSE}
quit(save = "no")
```
